changetime/urls.py
from django.conf.urls import url

from . import views

app_name = 'changetime'
urlpatterns = [
	url(r'^(?P<pk>[0-9]+)/$', views.ModifyView.as_view(), name='modify'),
	url(r'^/change/$', views.change, name='change'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
]

changetime/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
import datetime
from django.utils import timezone

class TimeDatas(models.Model):
	change_time = models.DateTimeField('Change')
	def is_early_time(self):
		now = timezone.now();
		return now >= self.change_time

changetime/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import TimeDatas

# Create your views here.
class ModifyView(generic.DetailView):
	model = TimeDatas
	template_name = 'changetime/modify.html'

class ResultsView(generic.DetailView):
    model = TimeDatas
    template_name = 'changetime/results.html'

def change(request):
	changetime = request.POST['modifytime']
	return render(request, 'changetime/results.html', {'changetime': changetime,})
	

changetime/templates/changetime/modify.html
<h1>修改服务器时间</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'changetime:change' %}" method="post">
{% csrf_token %}
<input type="date" name="modifytime" id="modify1" value="1" />
<label>修改时间</label>

<input type="submit" value="Modify" />
</form>

changetime/templates/changetime/results.html
<h1>修改时间成功:{{changetime}} </h1>